extends: vm3-extres-source-261008

conflict_resolvers: []

queue_rules:
  - name: vm3-extres-optout-261008
    merge_method: merge-batch
    batch_size: 2
    batch_max_wait_time: 60 sec
    queue_conditions:
      - base = vm3-extres-base-261008
      - title = VM3 EXTRES OPTOUT 261008
    merge_conditions:
      - check-success = vm3-extres-never-261008
